//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Loads = new HashSet<Load>();
        }
    
        public int DriverId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LicenseExpireDate { get; set; }
        public System.DateTime TdgTrainingDate { get; set; }
        public Nullable<System.DateTime> WhimsTrainingDate { get; set; }
        public int RegionId { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string CreatedByGlobalId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByGlobalId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Loads { get; set; }
    }
}
