//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LicenseExpireDate { get; set; }
        public Nullable<System.DateTime> TdgTrainingDate { get; set; }
        public Nullable<System.DateTime> WhmisTrainingDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
