//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderId { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<long> LoadId { get; set; }
        public Nullable<int> LoadSort { get; set; }
        public string OrderNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustAddress { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public int WeightKg { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool IsDangerousGoods { get; set; }
        public string Notes { get; set; }
        public string CreatedByGlobalId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedByGlobalId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsCustomerPickup { get; set; }
        public Nullable<int> R4OrderLineId { get; set; }
        public Nullable<int> LineNo { get; set; }
    
        public virtual Load Load { get; set; }
        public virtual Region Region { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
