//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        public int TrailerId { get; set; }
        public string TrailerDescription { get; set; }
        public int TrailerTypeId { get; set; }
        public int Volume { get; set; }
        public int UnitOfMeasureId { get; set; }
        public int CapacityKg { get; set; }
        public string AxlesDescription { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TrailerType TrailerType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
