//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettingId { get; set; }
        public int UserLoginId { get; set; }
        public string SettingCode { get; set; }
        public string SettingValue { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
