//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truckload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserLoginId { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public int AccessLevelId { get; set; }
        public byte[] HashPassword { get; set; }
        public System.Guid Salt { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
    }
}
